CREATE SET TABLE tpch.part ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      P_PARTKEY INTEGER NOT NULL,
      P_NAME VARCHAR(55) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      P_MFGR CHAR(25) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      P_BRAND CHAR(10) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      P_TYPE VARCHAR(25) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      P_SIZE INTEGER NOT NULL,
      P_CONTAINER CHAR(10) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      P_RETAILPRICE DECIMAL(15,2) NOT NULL,
      P_COMMENT VARCHAR(23) CHARACTER SET LATIN CASESPECIFIC NOT NULL)
UNIQUE PRIMARY INDEX ( P_PARTKEY );