CREATE SET TABLE tpch.region ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      R_REGIONKEY INTEGER NOT NULL,
      R_NAME CHAR(25) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      R_COMMENT VARCHAR(152) CHARACTER SET LATIN CASESPECIFIC NOT NULL)
UNIQUE PRIMARY INDEX ( R_REGIONKEY );