CREATE SET TABLE tpch.supplier ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      S_SUPPKEY INTEGER NOT NULL,
      S_NAME CHAR(25) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      S_ADDRESS VARCHAR(40) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      S_NATIONKEY INTEGER NOT NULL,
      S_PHONE CHAR(15) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      S_ACCTBAL DECIMAL(15,2) NOT NULL,
      S_COMMENT VARCHAR(101) CHARACTER SET LATIN CASESPECIFIC NOT NULL)
UNIQUE PRIMARY INDEX ( S_SUPPKEY );