CREATE SET TABLE tpch.lineitem ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      L_ORDERKEY INTEGER NOT NULL,
      L_PARTKEY INTEGER NOT NULL,
      L_SUPPKEY INTEGER NOT NULL,
      L_LINENUMBER INTEGER NOT NULL,
      L_QUANTITY DECIMAL(15,2) NOT NULL,
      L_EXTENDEDPRICE DECIMAL(15,2) NOT NULL,
      L_DISCOUNT DECIMAL(15,2) NOT NULL,
      L_TAX DECIMAL(15,2) NOT NULL,
      L_RETURNFLAG CHAR(1) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      L_LINESTATUS CHAR(1) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      L_SHIPDATE DATE FORMAT 'yyyy-mm-dd' NOT NULL,
      L_COMMITDATE DATE FORMAT 'yyyy-mm-dd' NOT NULL,
      L_RECEIPTDATE DATE FORMAT 'yyyy-mm-dd' NOT NULL,
      L_SHIPINSTRUCT CHAR(25) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      L_SHIPMODE CHAR(10) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      L_COMMENT VARCHAR(44) CHARACTER SET LATIN CASESPECIFIC NOT NULL)
PRIMARY INDEX ( L_ORDERKEY );