CREATE SET TABLE tpch.nation ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      N_NATIONKEY INTEGER NOT NULL,
      N_NAME CHAR(25) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
      N_REGIONKEY INTEGER NOT NULL,
      N_COMMENT VARCHAR(152) CHARACTER SET LATIN CASESPECIFIC NOT NULL)
PRIMARY INDEX ( N_NATIONKEY );