CREATE SET TABLE tpch.partsupp ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PS_PARTKEY INTEGER NOT NULL,
      PS_SUPPKEY INTEGER NOT NULL,
      PS_AVAILQTY INTEGER NOT NULL,
      PS_SUPPLYCOST DECIMAL(15,2) NOT NULL,
      PS_COMMENT VARCHAR(199) CHARACTER SET LATIN CASESPECIFIC NOT NULL)
PRIMARY INDEX ( PS_PARTKEY );